import { createHash } from 'node:crypto';
import { readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  SEASON_AI_VERSION,
  SEASON_ROSTER_GENERATION_VERSION,
  SEASON_ROSTER_TARGETS_VERSION,
  seasonDraftCatalogSchema,
  seasonLeagueSchema,
  seasonRosterTargetsSchema,
  type SeasonRosterRole,
  type SeasonRosterTargets,
} from '@hoop-rush/data-contracts';
import { generateAiLeague } from '@hoop-rush/engine';
import {
  seasonDraftReproduceReportSchema,
  seasonRostersAuditReportSchema,
  seasonRostersCalibrateReportSchema,
  seasonRostersGenerateReportSchema,
} from './report-schemas.ts';
import { jsonPayload, REPO_ROOT, runCli, TMP } from './cli-test-helpers.ts';
import { fixtureHumanRoster } from './commands/season-data.ts';

/**
 * CLI integration tests for the Season Run roster commands (spec/2.0 M2.1,
 * M2.4 roster-generation-v2): `season draft reproduce`, `season rosters
 * generate`, `season rosters audit`, and `season rosters calibrate` against
 * the authoritative engine with a hand-built `roster-targets-v2` artifact.
 * The committed static artifacts are regenerated by the coordinator; these
 * tests never commit a new static artifact and never touch the packaged
 * manifest or targets files (all fixtures live under the scratch TMP dir).
 */

const DRAFT_COMMANDS = join(REPO_ROOT, 'tools/cli/src/fixtures/season-draft-commands.json');
const DRAFT_FINALIZED = join(REPO_ROOT, 'tools/cli/src/fixtures/season-draft-finalized.json');
const MANIFEST = join(REPO_ROOT, 'apps/web/static/data/manifest.json');
const CATALOG = join(REPO_ROOT, 'apps/web/static/data/season/draft-catalog.json');
const LEAGUE = join(REPO_ROOT, 'apps/web/static/data/season/league.json');
const SEED = 'd00d2026a1b2c3d4e5f60718293a4b5c6';

const ROLES: readonly SeasonRosterRole[] = [
  'primary-creation',
  'secondary-creation',
  'perimeter-shooting',
  'rim-finishing-interior-scoring',
  'perimeter-defense',
  'interior-defense',
  'offensive-rebounding',
  'defensive-rebounding',
];

/** Schema-valid hand-built `roster-targets-v2` artifact (frozen literal policy). */
function handBuiltTargets(): SeasonRosterTargets {
  const bandRange = (range: [number, number]): { range: [number, number]; median: number } => ({
    range,
    median: (range[0] + range[1]) / 2,
  });
  return {
    schemaVersion: 2,
    targetsVersion: SEASON_ROSTER_TARGETS_VERSION,
    policy: {
      bandQuotas: {
        solo: { contender: 4, playoff: 8, average: 10, weaker: 7 },
        duo: { contender: 4, playoff: 8, average: 9, weaker: 7 },
      },
      guaranteedAnchors: { contender: 2, playoff: 1, average: 0, weaker: 0 },
      extraEliteRollProbability: { contender: 0.65, playoff: 0.35, average: 0.2, weaker: 0.08 },
      tierRanges: {
        contender: { elite: [2, 4], strong: [5, 8], useful: [6, 10] },
        playoff: { elite: [1, 2], strong: [4, 7], useful: [7, 10] },
        average: { elite: [0, 1], strong: [3, 6], useful: [8, 11] },
        weaker: { elite: [0, 1], strong: [1, 4], useful: [7, 10] },
      },
      identityPriorityRoles: {
        'star-chaser': ['primary-creation', 'perimeter-shooting', 'rim-finishing-interior-scoring'],
        'shooting-first': ['perimeter-shooting', 'secondary-creation', 'primary-creation'],
        'defense-first': ['perimeter-defense', 'interior-defense', 'defensive-rebounding'],
        'depth-builder': [...ROLES],
        continuity: [...ROLES],
        'active-trader': [...ROLES],
      },
      roleCoverageThreshold: 35,
      completionTargets: { guards: 4, forwards: 4, centers: 3 },
      poolSize: 20,
      rosterSize: 10,
      percentileTiers: { elite: 0.9, strong: 0.75, useful: 0.5 },
      bandPoolScoreCaps: { contender: 100, playoff: 92, average: 84, weaker: 74 },
      maxPoolStrengthOutliers: 4,
      maxRosterStrengthOutliers: 2,
      nodeBudgets: { anchorMatching: 20000, poolRepair: 40000, rosterSelection: 600000 },
    },
    calibration: {
      calibrationSeedCount: 4,
      validationSeedCount: 2,
      generatedAtIso: '2026-01-01T00:00:00.000Z',
      aiVersion: SEASON_AI_VERSION,
      rosterGenerationVersion: SEASON_ROSTER_GENERATION_VERSION,
      gates: {
        failureRateMax: 0,
        minBandSeparation: 3,
        anchorFulfillmentMin: 1,
        extraEliteRateTolerance: 0.05,
        heldOutPassShare: 0.95,
        orderInvarianceFailuresMax: 0,
        superTeamIncidenceMax: 0.08,
      },
    },
    measured: {
      bands: {
        contender: { ...bandRange([50, 80]), eliteShare: 0.5, strongShare: 0.5, usefulShare: 0.9 },
        playoff: { ...bandRange([45, 75]), eliteShare: 0.2, strongShare: 0.5, usefulShare: 0.9 },
        average: { ...bandRange([40, 70]), eliteShare: 0.05, strongShare: 0.4, usefulShare: 0.9 },
        weaker: { ...bandRange([35, 65]), eliteShare: 0.05, strongShare: 0.3, usefulShare: 0.85 },
      },
      identities: {
        'star-chaser': bandRange([40, 80]),
        'depth-builder': bandRange([40, 75]),
        'defense-first': bandRange([40, 75]),
        'shooting-first': bandRange([40, 75]),
        continuity: bandRange([40, 75]),
        'active-trader': bandRange([40, 75]),
      },
      anchorFulfillment: 1,
      extraEliteRate: 0.27,
      superTeamIncidence: 0,
      poolLegalityFailures: 0,
      selectionFailures: 0,
      generationFailures: 0,
    },
  };
}

function sha256Hex(content: Buffer | string): string {
  return createHash('sha256').update(content).digest('hex');
}

/**
 * Writes the hand-built targets to the scratch dir and a scratch manifest
 * whose `season` section points at the real catalog (hash-copied from the
 * packaged manifest) and at the scratch targets artifact. Returns the
 * scratch manifest path; `withManifestRosterTargets=false` writes the
 * manifest without a `rosterTargets` entry (missing-artifact failure case).
 */
function writeScratchManifest(
  targets: SeasonRosterTargets,
  options: { omitRosterTargets?: boolean } = {},
): string {
  const targetsPath = join(TMP, 'roster-targets.json');
  const targetsBytes = `${JSON.stringify(targets, null, 2)}\n`;
  writeFileSync(targetsPath, targetsBytes);
  const manifest = JSON.parse(readFileSync(MANIFEST, 'utf8')) as {
    season?: Record<string, { url?: string; contentHash?: string }>;
  };
  const season = {
    draftCatalog: manifest.season?.draftCatalog,
    ...(options.omitRosterTargets === true
      ? {}
      : {
          rosterTargets: {
            url: 'roster-targets.json',
            contentHash: sha256Hex(targetsBytes),
          },
        }),
  };
  const manifestPath = join(TMP, 'manifest.json');
  writeFileSync(manifestPath, `${JSON.stringify({ ...manifest, season }, null, 2)}\n`);
  return manifestPath;
}

describe('cli: season rosters generate (roster-generation-v2)', () => {
  it('previews a deterministic generation against the verified targets artifact', async () => {
    const manifestPath = writeScratchManifest(handBuiltTargets());
    const { code, stdout } = await runCli([
      'season',
      'rosters',
      'generate',
      '--seed',
      SEED,
      '--draft',
      DRAFT_FINALIZED,
      '--manifest',
      manifestPath,
      '--format',
      'json',
    ]);
    expect(code).toBe(0);
    const payload = seasonRostersGenerateReportSchema.parse(jsonPayload(stdout));
    expect(payload.pass).toBe(true);
    expect(payload.wrote).toBe(false);
    expect(payload.teams).toBe(30);
    expect(payload.ownershipRows).toBe(300);
    expect(payload.pools).toBe(29);
    expect(payload.anchorsTotal).toBeGreaterThanOrEqual(16);
    expect(payload.repairCount).toBeGreaterThanOrEqual(0);
    // Deterministic: a second run produces the identical digest.
    const second = await runCli([
      'season',
      'rosters',
      'generate',
      '--seed',
      SEED,
      '--draft',
      DRAFT_FINALIZED,
      '--manifest',
      manifestPath,
      '--format',
      'json',
    ]);
    expect(seasonRostersGenerateReportSchema.parse(jsonPayload(second.stdout)).digest).toBe(
      payload.digest,
    );
  }, 300_000);

  it('rejects a tampered targets artifact with a typed failure', async () => {
    const manifestPath = writeScratchManifest(handBuiltTargets());
    const targetsPath = join(TMP, 'roster-targets.json');
    const tampered = JSON.parse(readFileSync(targetsPath, 'utf8')) as SeasonRosterTargets;
    tampered.measured.anchorFulfillment = 0.5;
    writeFileSync(targetsPath, `${JSON.stringify(tampered, null, 2)}\n`);
    const { code, stdout, stderr } = await runCli([
      'season',
      'rosters',
      'generate',
      '--seed',
      SEED,
      '--draft',
      DRAFT_FINALIZED,
      '--manifest',
      manifestPath,
      '--format',
      'json',
    ]);
    expect(code).toBe(2);
    const report = JSON.parse((stdout + stderr).slice((stdout + stderr).indexOf('{'))) as {
      failures: string[];
    };
    expect(report.failures[0]).toContain('content hash mismatch');
  });

  it('rejects a manifest without a rosterTargets entry with a typed failure', async () => {
    const manifestPath = writeScratchManifest(handBuiltTargets(), { omitRosterTargets: true });
    const { code, stderr } = await runCli([
      'season',
      'rosters',
      'generate',
      '--seed',
      SEED,
      '--draft',
      DRAFT_FINALIZED,
      '--manifest',
      manifestPath,
      '--format',
      'json',
    ]);
    expect(code).toBe(2);
    expect(stderr).toContain('no season.rosterTargets entry');
  });

  it('rejects a non-hex seed with a usage error', async () => {
    const manifestPath = writeScratchManifest(handBuiltTargets());
    const { code, stderr } = await runCli([
      'season',
      'rosters',
      'generate',
      '--seed',
      'not-hex',
      '--draft',
      DRAFT_FINALIZED,
      '--manifest',
      manifestPath,
    ]);
    expect(code).toBe(2);
    expect(stderr).toContain('--seed must be a hex seed');
  });
});

describe('cli: season rosters audit (roster-generation-v2)', () => {
  it('audits an engine-generated league with zero failures', async () => {
    const targets = handBuiltTargets();
    const catalog = seasonDraftCatalogSchema.parse(JSON.parse(readFileSync(CATALOG, 'utf8')));
    const league = seasonLeagueSchema.parse(JSON.parse(readFileSync(LEAGUE, 'utf8')));
    const humanRoster = fixtureHumanRoster(catalog);
    const humanRosters = [{ franchiseId: 'lakers', playerVersionIds: humanRoster }];
    const result = generateAiLeague({
      seed: SEED,
      catalog,
      league,
      humanFranchiseIds: ['lakers'],
      humanRosters,
      targets,
    });
    const resultPath = join(TMP, 'generated-league.json');
    writeFileSync(resultPath, `${JSON.stringify(result, null, 2)}\n`);
    const manifestPath = writeScratchManifest(targets);
    const { code, stdout } = await runCli([
      'season',
      'rosters',
      'audit',
      '--input',
      resultPath,
      '--manifest',
      manifestPath,
      '--human-franchises',
      'lakers',
      '--format',
      'json',
    ]);
    expect(code).toBe(0);
    const payload = seasonRostersAuditReportSchema.parse(jsonPayload(stdout));
    expect(payload.pass).toBe(true);
    expect(payload.auditFailures).toBe(0);
    expect(payload.digestVerified).toBe(true);
    expect(payload.teams).toBe(30);
    expect(payload.ownershipRows).toBe(300);
    expect(payload.pools).toBe(29);
    expect(payload.poolFailures).toBe(0);
    expect(payload.anchorFailures).toBe(0);
    expect(payload.tierFailures).toBe(0);
    expect(payload.exclusivityFailures).toBe(0);
    expect(payload.selectionFailures).toBe(0);
  }, 300_000);

  it('fails on a tampered digest with a nonzero exit', async () => {
    const targets = handBuiltTargets();
    const catalog = seasonDraftCatalogSchema.parse(JSON.parse(readFileSync(CATALOG, 'utf8')));
    const league = seasonLeagueSchema.parse(JSON.parse(readFileSync(LEAGUE, 'utf8')));
    const humanRoster = fixtureHumanRoster(catalog);
    const result = generateAiLeague({
      seed: SEED,
      catalog,
      league,
      humanFranchiseIds: ['lakers'],
      humanRosters: [{ franchiseId: 'lakers', playerVersionIds: humanRoster }],
      targets,
    });
    const tampered = { ...result, digest: '0'.repeat(32) };
    const resultPath = join(TMP, 'generated-league.tampered.json');
    writeFileSync(resultPath, `${JSON.stringify(tampered, null, 2)}\n`);
    const manifestPath = writeScratchManifest(targets);
    const { code, stdout, stderr } = await runCli([
      'season',
      'rosters',
      'audit',
      '--input',
      resultPath,
      '--manifest',
      manifestPath,
      '--human-franchises',
      'lakers',
      '--format',
      'json',
    ]);
    expect(code).toBe(1);
    const payload = seasonRostersAuditReportSchema.parse(jsonPayload(stdout, stderr));
    expect(payload.pass).toBe(false);
    expect(payload.digestVerified).toBe(false);
    expect(payload.auditFailures).toBeGreaterThan(0);
  });
});

describe('cli: season rosters calibrate (roster-generation-v2)', () => {
  it('runs a small cohort, evaluates gates, and rewrites only measured', async () => {
    const targets = handBuiltTargets();
    const targetsPath = join(TMP, 'calibration-targets.json');
    writeFileSync(targetsPath, `${JSON.stringify(targets, null, 2)}\n`);
    const outPath = join(TMP, 'calibration-out.json');
    const { code, stdout, stderr } = await runCli([
      'season',
      'rosters',
      'calibrate',
      '--calibration-seeds',
      '4',
      '--validation-seeds',
      '2',
      '--workers',
      '2',
      '--targets',
      targetsPath,
      '--out',
      outPath,
      '--format',
      'json',
    ]);
    expect([0, 1]).toContain(code);
    const payload = seasonRostersCalibrateReportSchema.parse(jsonPayload(stdout, stderr));
    expect(payload.calibrationSeeds).toBe(4);
    expect(payload.validationSeeds).toBe(2);
    expect(payload.measured.generationFailures).toBe(0);
    expect(payload.measured.poolLegalityFailures).toBe(0);
    expect(payload.measured.selectionFailures).toBe(0);
    expect(payload.gates.poolLegality).toBe(true);
    expect(payload.gates.selectionLegality).toBe(true);
    expect(payload.gates.failureRate).toBe(true);
    expect(payload.validateOnly).toBe(false);
    expect(payload.targetsWritten).toBe(true);
    expect(payload.targetsPath).toBe(outPath);
    // The rewritten artifact preserves the policy verbatim and carries the
    // recomputed measured facts.
    const rewritten = seasonRosterTargetsSchema.parse(JSON.parse(readFileSync(outPath, 'utf8')));
    expect(rewritten.policy).toEqual(targets.policy);
    expect(rewritten.calibration.gates).toEqual(targets.calibration.gates);
    expect(rewritten.measured.generationFailures).toBe(0);
  }, 300_000);

  it('--validate evaluates gates without rewriting the artifact', async () => {
    const targets = handBuiltTargets();
    const targetsPath = join(TMP, 'validate-targets.json');
    const targetsBytes = `${JSON.stringify(targets, null, 2)}\n`;
    writeFileSync(targetsPath, targetsBytes);
    const { code, stdout, stderr } = await runCli([
      'season',
      'rosters',
      'calibrate',
      '--calibration-seeds',
      '4',
      '--validation-seeds',
      '2',
      '--workers',
      '2',
      '--targets',
      targetsPath,
      '--validate',
      '--format',
      'json',
    ]);
    expect([0, 1]).toContain(code);
    const payload = seasonRostersCalibrateReportSchema.parse(jsonPayload(stdout, stderr));
    expect(payload.validateOnly).toBe(true);
    expect(payload.targetsWritten).toBe(false);
    expect(payload.targetsPath).toBe(null);
    // Byte-compare: the artifact is untouched in validate mode.
    expect(readFileSync(targetsPath, 'utf8')).toBe(targetsBytes);
  }, 300_000);
});

describe('cli: season draft reproduce', () => {
  it('reproduces the committed fixture with the exact digest', async () => {
    const manifestPath = writeScratchManifest(handBuiltTargets());
    const { code, stdout } = await runCli([
      'season',
      'draft',
      'reproduce',
      '--input',
      DRAFT_COMMANDS,
      '--manifest',
      manifestPath,
      '--format',
      'json',
    ]);
    expect(code).toBe(0);
    const payload = seasonDraftReproduceReportSchema.parse(jsonPayload(stdout));
    expect(payload.pass).toBe(true);
    expect(payload.identical).toBe(true);
    expect(payload.finalDigest).toBe('95396ddde716fe01829f4d2fcb6b8e8d');
    expect(payload.acceptedCount).toBe(payload.commandCount);
    expect(payload.rejectedCount).toBe(0);
    expect(payload.offers).toHaveLength(10);
    expect(payload.picks).toHaveLength(10);
  });

  it('rejects malformed inputs with a usage error', async () => {
    const bad = join(REPO_ROOT, 'tools/cli/src/fixtures/season-draft-finalized.json');
    const { code, stderr } = await runCli(['season', 'draft', 'reproduce', '--input', bad]);
    expect(code).toBe(2);
    expect(stderr).toContain('commands input fails the schema');
  });

  it('reports divergences with a nonzero exit', async () => {
    const fixture = JSON.parse(readFileSync(DRAFT_COMMANDS, 'utf8')) as {
      expected: { finalDigest: string; finalRevision: number };
    };
    const manifestPath = writeScratchManifest(handBuiltTargets());
    const tmpPath = join(TMP, 'season-draft-commands.divergence.json');
    try {
      writeFileSync(
        tmpPath,
        JSON.stringify({
          ...fixture,
          expected: { finalDigest: '0'.repeat(32), finalRevision: fixture.expected.finalRevision },
        }),
      );
      const { code, stdout, stderr } = await runCli([
        'season',
        'draft',
        'reproduce',
        '--input',
        tmpPath,
        '--manifest',
        manifestPath,
        '--format',
        'json',
      ]);
      expect(code).toBe(1);
      const payload = seasonDraftReproduceReportSchema.parse(jsonPayload(stdout, stderr));
      expect(payload.identical).toBe(false);
      expect(payload.divergences.length).toBeGreaterThan(0);
    } finally {
      rmSync(tmpPath, { force: true });
    }
  });
});
