import { z } from 'zod';
import {
  SEASON_CAMPAIGN_TARGETS_VERSION,
  SEASON_EFFECT_TARGETS_LEGACY_VERSION,
  SEASON_EFFECT_TARGETS_VERSION,
  SEASON_FREE_AGENCY_TARGETS_VERSION,
  SEASON_INFLUENCE_TARGETS_VERSION,
  SEASON_INJURY_TARGETS_VERSION,
  SEASON_POSTSEASON_TARGETS_VERSION,
  SEASON_TRADE_TARGETS_VERSION,
  franchiseIdSchema,
  playerVersionIdSchema,
  reconstructionHoldoutSchema,
  reconstructionPriorsSchema,
  seasonFoulOutSchema,
  seasonForfeitTriggerSchema,
  seasonObjectiveIdSchema,
  seasonRotationDeviationReasonSchema,
  seasonRotationDeviationSchema,
  seasonRotationPresetSchema,
  seasonSubstitutionSchema,
  seasonUnitStintSchema,
} from '@hoop-rush/data-contracts';
export const simGameReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('sim game'),
  seed: z.string().min(1).max(64),
  engineVersion: z.string().min(1).max(64),
  dataVersion: z.string().min(1).max(64),
  profileVersion: z.string().min(1).max(64),
  fixture: z.string().min(1).max(64),
  result: z.unknown(),
  invariants: z.array(z.string()),
  timingMs: z.number().nonnegative(),
});
export type SimGameReport = z.infer<typeof simGameReportSchema>;
export const simBatchReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('sim batch'),
  fixture: z.string().min(1).max(64),
  seedFrom: z.number().int(),
  seedTo: z.number().int(),
  workers: z.number().int().min(1),
  engineVersion: z.string().min(1).max(64),
  games: z.number().int().nonnegative(),
  homeWins: z.number().int().nonnegative(),
  awayWins: z.number().int().nonnegative(),
  overtimeGames: z.number().int().nonnegative(),
  homeWinRate: z.number(),
  averagePoints: z.number(),
  averagePossessions: z.number(),
  averageMargin: z.number(),
  invariantFailures: z.number().int().nonnegative(),
});
export type SimBatchReport = z.infer<typeof simBatchReportSchema>;
export const simDiagnoseReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('sim diagnose'),
  fixture: z.string().min(1).max(64),
  samples: z.number().int().nonnegative(),
  engineVersion: z.string().min(1).max(64),
  profileVersion: z.string().min(1).max(64),
  players: z.array(
    z.object({
      playerId: z.string().min(1).max(64),
      displayName: z.string().min(1).max(96),
      archetype: z.string().min(1).max(32),
      games: z.number().int().nonnegative(),
      pointsPerGame: z.number(),
      usagePerGame: z.number(),
      usageShare: z.number(),
      fieldGoalPct: z.number(),
      threePointRate: z.number(),
      freeThrowRate: z.number(),
      assistsPerGame: z.number(),
      assistConversion: z.number(),
      assistOpportunitiesPerGame: z.number(),
      offensiveReboundPct: z.number(),
      defensiveReboundPct: z.number(),
      contestedPerGame: z.number(),
      stealsPerGame: z.number(),
      turnoversPerGame: z.number(),
      topZone: z.string().min(1).max(32),
      zoneMix: z.array(
        z.object({
          zone: z.string().min(1).max(16),
          attempts: z.number().int(),
          makes: z.number().int(),
          pct: z.number(),
        }),
      ),
    }),
  ),
  team: z.object({
    averagePointsPerGame: z.number(),
    averagePossessionsPerGame: z.number(),
    averageTeamMissesPerGame: z.number(),
  }),
  spread: z.object({ topToLastUsageRatio: z.number() }),
});
export type SimDiagnoseReport = z.infer<typeof simDiagnoseReportSchema>;
export const simSeasonReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('sim season'),
  fixture: z.string().min(1).max(64),
  seasons: z.number().int().nonnegative(),
  engineVersion: z.string().min(1).max(64),
  profileVersion: z.string().min(1).max(64),
  varianceRatioBand: z.tuple([z.number(), z.number()]),
  rows: z.array(
    z.object({
      season: z.number().int().positive(),
      players: z.array(
        z.object({
          playerId: z.string().min(1).max(64),
          displayName: z.string().min(1).max(96),
          games: z.number().int().nonnegative(),
          pointsPerGame: z.number(),
          fieldGoalPct: z.number(),
          threePointPct: z.number(),
          freeThrowPct: z.number(),
          assistsPerGame: z.number(),
          reboundsPerGame: z.number(),
          turnoversPerGame: z.number(),
          usagePerGame: z.number(),
          variance: z.object({
            fieldGoalRatio: z.number(),
            freeThrowRatio: z.number(),
          }),
        }),
      ),
    }),
  ),
});
export type SimSeasonReport = z.infer<typeof simSeasonReportSchema>;
export const replayReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('replay'),
  seed: z.string().min(1).max(64),
  engineVersion: z.string().min(1).max(64),
  identical: z.boolean(),
  firstDifference: z.string().nullable(),
  expectedValue: z.unknown().nullable(),
  actualValue: z.unknown().nullable(),
});
export type ReplayReport = z.infer<typeof replayReportSchema>;
export const calibrationMetricStatusSchema = z.enum(['pass', 'fail', 'skippedInsufficientSample']);
export type CalibrationMetricStatus = z.infer<typeof calibrationMetricStatusSchema>;
export const calibrationMetricSchema = z.object({
  key: z.string().min(1).max(64),
  target: z.number(),
  tolerance: z.number(),
  observed: z.number(),
  status: calibrationMetricStatusSchema,
  pass: z.boolean(),
  sample: z.number().int().nonnegative(),
  minimumSample: z.number().int().nonnegative(),
});
export type CalibrationMetric = z.infer<typeof calibrationMetricSchema>;
export const calibrateRunReportSchema = z.object({
  schemaVersion: z.literal(2),
  command: z.literal('calibrate run'),
  profileVersion: z.string().min(1).max(64),
  eraId: z.string().min(1).max(24),
  samples: z.number().int().nonnegative(),
  engineVersion: z.string().min(1).max(64),
  pass: z.boolean(),
  metrics: z.array(calibrationMetricSchema),
  openingOpponentWinRateVsStrongUser: z.number().nullable(),
  bracketDistribution: z
    .array(
      z.object({
        opponentId: z.string().min(1).max(64),
        recordedWinRate: z.number().min(0).max(1),
        observedWinRate: z.number().min(0).max(1),
        recordedPercentile: z.number().min(0).max(1),
      }),
    )
    .nullable(),
  bracketMedianObservedWinRate: z.number().nullable(),
  perfectRunRate: z.number().nullable(),
  challengeRuns: z.number().int().nonnegative(),
  invariantFailures: z.number().int().nonnegative(),
});
export type CalibrateRunReport = z.infer<typeof calibrateRunReportSchema>;
export const sensitivityMetricSchema = z.object({
  family: z.string().min(1).max(64),
  direction: z.string().min(1).max(64),
  baseValue: z.number(),
  changedValue: z.number(),
  relativeShift: z.number(),
  pass: z.boolean(),
});
export type SensitivityMetric = z.infer<typeof sensitivityMetricSchema>;
export const calibrateSensitivityReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('calibrate sensitivity'),
  samples: z.number().int().nonnegative(),
  engineVersion: z.string().min(1).max(64),
  pass: z.boolean(),
  metrics: z.array(sensitivityMetricSchema),
});
export type CalibrateSensitivityReport = z.infer<typeof calibrateSensitivityReportSchema>;
export const threePointCalibrateReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('calibrate three-point'),
  artifactVersion: z.string().min(1).max(64),
  written: z.boolean(),
  artifactPath: z.string().min(1),
  cohortSize: z.object({
    rows: z.number().int().nonnegative(),
    accuracyRows: z.number().int().nonnegative(),
    attemptRows: z.number().int().nonnegative(),
  }),
  gates: z.object({
    meanBiasNonPositiveAccuracy: z.boolean(),
    meanBiasNonPositiveTranslatedAttemptRate: z.boolean(),
    floorBelowEstablished: z.boolean(),
  }),
  floors: z.object({
    floor: z.number().min(0).max(1),
    zoneFloors: z.object({
      cornerThree: z.number().min(0).max(1),
      aboveBreakThree: z.number().min(0).max(1),
    }),
  }),
  ratingMapping: z.object({
    points: z
      .array(z.object({ accuracy: z.number().min(0).max(1), rating: z.number().min(0).max(100) }))
      .min(2),
    clampMin: z.number().min(0).max(100),
    clampMax: z.number().min(0).max(100),
  }),
  regularization: z.object({
    lambda: z.number().nonnegative(),
    maxIterations: z.number().int().positive(),
    convergenceTolerance: z.number().positive(),
  }),
  priors: reconstructionPriorsSchema,
  fitCohort: z.object({
    seasons: z.array(z.string().min(1).max(16)).length(5),
    description: z.string().min(1).max(256),
  }),
  holdout: reconstructionHoldoutSchema,
  generatedBy: z.string().min(1).max(256),
});
export type ThreePointCalibrateReport = z.infer<typeof threePointCalibrateReportSchema>;
export const simChallengeReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('sim challenge'),
  lineup: z.string().min(1).max(320),
  seed: z.string().min(1).max(64),
  eraId: z.string().min(1).max(64),
  chosenSeed: z.string().min(1).max(64),
  attempts: z.number().int().positive(),
  engineVersion: z.string().min(1).max(64),
  dataVersion: z.string().min(1).max(64),
  profileVersion: z.string().min(1).max(64),
  bracketVersion: z.string().min(1).max(64),
  scheduleVersion: z.string().min(1).max(64),
  record: z.object({
    wins: z.number().int().nonnegative(),
    losses: z.number().int().nonnegative(),
    gamesPlayed: z.number().int().nonnegative(),
  }),
  outcome: z.enum(['perfect', 'eliminated']),
  firstLossGameNumber: z.number().int().min(1).max(82).nullable(),
  playerTotals: z.array(
    z.object({
      playerId: z.string().min(1).max(64),
      gamesPlayed: z.number().int().nonnegative(),
      minutes: z.number().int().nonnegative(),
      points: z.number().int().nonnegative(),
      rebounds: z.number().int().nonnegative(),
      assists: z.number().int().nonnegative(),
      steals: z.number().int().nonnegative(),
      blocks: z.number().int().nonnegative(),
      turnovers: z.number().int().nonnegative(),
      fouls: z.number().int().nonnegative(),
      fieldGoals: z.object({
        made: z.number().int().nonnegative(),
        attempted: z.number().int().nonnegative(),
      }),
      threes: z.object({
        made: z.number().int().nonnegative(),
        attempted: z.number().int().nonnegative(),
      }),
      freeThrows: z.object({
        made: z.number().int().nonnegative(),
        attempted: z.number().int().nonnegative(),
      }),
    }),
  ),
  teamPossessions: z.number().int().nonnegative(),
  timingMs: z.number().nonnegative(),
  invariantFailures: z.number().int().nonnegative(),
});
export type SimChallengeReport = z.infer<typeof simChallengeReportSchema>;
export const bracketAuditReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('bracket audit'),
  dataVersion: z.string().min(1).max(64),
  bracketVersion: z.string().min(1).max(64),
  scheduleVersion: z.string().min(1).max(64),
  generationSeed: z.string().min(1).max(64),
  generationVersion: z.string().min(1).max(64),
  difficultyProfileVersion: z.string().min(1).max(64),
  opponents: z.array(
    z.object({
      opponentId: z.string().min(1).max(64),
      teamId: z.string().min(1).max(64),
      winRate: z.number().min(0).max(1),
      percentile: z.number().min(0).max(1),
      sampleCount: z.number().int().positive(),
    }),
  ),
  schedulePreview: z.array(z.string().min(1)).nullable(),
  leagueMedianPercentile: z.number().min(0).max(1),
  minPercentile: z.number().min(0).max(1),
  maxPercentile: z.number().min(0).max(1),
  teamPercentileBand: z.tuple([z.number().min(0).max(1), z.number().min(0).max(1)]),
  leagueMedianPercentileBand: z.tuple([z.number().min(0).max(1), z.number().min(0).max(1)]),
  openingOpponentUnchanged: z.boolean(),
  pass: z.boolean(),
});
export type BracketAuditReport = z.infer<typeof bracketAuditReportSchema>;
const benchmarkRegressionSchema = z.object({
  metric: z.enum(['medianMs', 'p95Ms']),
  measurement: z.enum(['poolCold', 'poolCached', 'singleGame', 'challenge82']),
  baselineMs: z.number().nonnegative(),
  currentMs: z.number().nonnegative(),
  noiseAllowanceMs: z.number().nonnegative(),
});
const benchmarkBaselineComparisonSchema = z.object({
  status: z.enum(['not-requested', 'matched', 'skipped-fingerprint', 'regressed']),
  fingerprintMatched: z.boolean(),
  baselineFingerprint: z.string().nullable(),
  regressions: z.array(benchmarkRegressionSchema),
});
const timingStatsSchema = z.object({
  sampleCount: z.number().int().nonnegative(),
  medianMs: z.number().nonnegative(),
  p95Ms: z.number().nonnegative(),
  minMs: z.number().nonnegative(),
  maxMs: z.number().nonnegative(),
});
export const benchmarkReportSchema = z.object({
  schemaVersion: z.literal(2),
  command: z.literal('benchmark'),
  environment: z.object({
    node: z.string().min(1).max(64),
    platform: z.string().min(1).max(64),
    arch: z.string().min(1).max(64),
    cpus: z.number().int().positive(),
    fingerprint: z.string().min(1).max(256),
  }),
  engineVersion: z.string().min(1).max(64),
  dataVersion: z.string().min(1).max(64),
  profileVersion: z.string().min(1).max(64),
  bracketVersion: z.string().min(1).max(64),
  scheduleVersion: z.string().min(1).max(64),
  fixture: z.string().min(1).max(64),
  samples: z.number().int().nonnegative(),
  workers: z.number().int().min(1),
  poolCold: timingStatsSchema,
  poolCached: timingStatsSchema,
  singleGame: timingStatsSchema,
  challenge82: timingStatsSchema,
  heapUsedMb: z.number().nonnegative(),
  heap: z.object({
    beforeMb: z.number().nonnegative(),
    afterMb: z.number().nonnegative(),
    deltaMb: z.number(),
  }),
  baselineComparison: benchmarkBaselineComparisonSchema,
});
export type BenchmarkReport = z.infer<typeof benchmarkReportSchema>;
export const bracketGenerateReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('bracket generate'),
  seed: z.string().min(1).max(64),
  generationVersion: z.string().min(1).max(64),
  dataVersion: z.string().min(1).max(64),
  bracketVersion: z.string().min(1).max(64),
  scheduleVersion: z.string().min(1).max(64),
  contentHash: z.string().regex(/^[0-9a-f]{64}$/),
  opponents: z.array(
    z.object({
      opponentId: z.string().min(1).max(64),
      teamId: z.string().min(1).max(64),
      winRate: z.number().min(0).max(1),
      percentile: z.number().min(0).max(1),
      players: z.array(z.string().min(1).max(64)),
    }),
  ),
  schedule: z.array(z.string().min(1).max(64)),
});
export type BracketGenerateReport = z.infer<typeof bracketGenerateReportSchema>;
export const seasonScheduleGenerateReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('season schedule generate'),
  seed: z.string().regex(/^[0-9a-f]{16,64}$/),
  scheduleVersion: z.string().min(1).max(64),
  formulaVersion: z.string().min(1).max(64),
  leagueVersion: z.string().min(1).max(64),
  rounds: z.number().int().positive(),
  games: z.number().int().positive(),
  sha256: z.string().regex(/^[0-9a-f]{64}$/),
  wrote: z.boolean(),
  outPath: z.string().nullable(),
  pass: z.boolean(),
});
export type SeasonScheduleGenerateReport = z.infer<typeof seasonScheduleGenerateReportSchema>;
export const seasonScheduleAuditReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('season schedule audit'),
  scheduleVersion: z.string().min(1).max(64),
  formulaVersion: z.string().min(1).max(64),
  leagueVersion: z.string().min(1).max(64),
  seed: z.string().regex(/^[0-9a-f]{16,64}$/),
  rounds: z.number().int().positive(),
  games: z.number().int().positive(),
  auditFailures: z.number().int().nonnegative(),
  regenerationIdentical: z.boolean(),
  manifestVerified: z.boolean().nullable(),
  pass: z.boolean(),
});
export type SeasonScheduleAuditReport = z.infer<typeof seasonScheduleAuditReportSchema>;
export const seasonDraftReproduceReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('season draft reproduce'),
  seed: z.string().regex(/^[0-9a-f]{16,64}$/),
  catalogVersion: z.string().min(1).max(64),
  commandCount: z.number().int().nonnegative(),
  acceptedCount: z.number().int().nonnegative(),
  rejectedCount: z.number().int().nonnegative(),
  finalRevision: z.number().int().nonnegative(),
  finalStatus: z.string().min(1).max(32),
  finalDigest: z.string().regex(/^[0-9a-f]{32}$/),
  expectedDigest: z
    .string()
    .regex(/^[0-9a-f]{32}$/)
    .nullable(),
  identical: z.boolean(),
  offers: z.array(
    z.object({
      participantId: z.string().min(1).max(64),
      round: z.number().int().min(1).max(10),
      pickOrdinal: z.number().int().min(1).max(10),
      seedPath: z.array(z.string().min(1)).min(1),
      cards: z.array(
        z.object({
          playerVersionId: z.string().min(1).max(64),
          selectable: z.boolean(),
          coverageReason: z.string().min(1).max(256).nullable(),
        }),
      ),
    }),
  ),
  picks: z.array(
    z.object({
      participantId: z.string().min(1).max(64),
      round: z.number().int().min(1).max(10),
      playerVersionId: z.string().min(1).max(64),
    }),
  ),
  rejections: z.array(
    z.object({
      commandId: z.string().min(1).max(64),
      errorCode: z.string().min(1).max(64),
      message: z.string().min(1).max(512),
    }),
  ),
  divergences: z.array(z.string().min(1)),
  pass: z.boolean(),
});
export type SeasonDraftReproduceReport = z.infer<typeof seasonDraftReproduceReportSchema>;
export const seasonRostersGenerateReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('season rosters generate'),
  seed: z.string().regex(/^[0-9a-f]{16,64}$/),
  teams: z.number().int().positive(),
  ownershipRows: z.number().int().positive(),
  pools: z.number().int().nonnegative(),
  anchorsTotal: z.number().int().nonnegative(),
  repairCount: z.number().int().nonnegative(),
  digest: z.string().regex(/^[0-9a-f]{32}$/),
  diagnostics: z.object({
    teamsGenerated: z.number().int().nonnegative(),
    teamsRepaired: z.number().int().nonnegative(),
    backtracks: z.number().int().nonnegative(),
    nodesVisited: z.number().int().nonnegative(),
  }),
  wrote: z.boolean(),
  outPath: z.string().nullable(),
  pass: z.boolean(),
});
export type SeasonRostersGenerateReport = z.infer<typeof seasonRostersGenerateReportSchema>;
export const seasonRostersAuditReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('season rosters audit'),
  input: z.string().min(1),
  teams: z.number().int().positive(),
  ownershipRows: z.number().int().positive(),
  pools: z.number().int().nonnegative(),
  quotaFailures: z.number().int().nonnegative(),
  identityFailures: z.number().int().nonnegative(),
  selectionFailures: z.number().int().nonnegative(),
  legalityFailures: z.number().int().nonnegative(),
  roleCoverageFailures: z.number().int().nonnegative(),
  rotationFailures: z.number().int().nonnegative(),
  poolFailures: z.number().int().nonnegative(),
  anchorFailures: z.number().int().nonnegative(),
  tierFailures: z.number().int().nonnegative(),
  exclusivityFailures: z.number().int().nonnegative(),
  versionFailures: z.number().int().nonnegative(),
  digestVerified: z.boolean(),
  auditFailures: z.number().int().nonnegative(),
  pass: z.boolean(),
});
export type SeasonRostersAuditReport = z.infer<typeof seasonRostersAuditReportSchema>;
const distributionEntrySchema = z.object({
  median: z.number().min(0).max(100),
  range: z.tuple([z.number().min(0).max(100), z.number().min(0).max(100)]),
  min: z.number().min(0).max(100),
  max: z.number().min(0).max(100),
  sample: z.number().int().nonnegative(),
});
const bandDistributionEntrySchema = distributionEntrySchema.extend({
  eliteShare: z.number().min(0).max(1),
  strongShare: z.number().min(0).max(1),
  usefulShare: z.number().min(0).max(1),
});
export const seasonRostersCalibrateReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('season rosters calibrate'),
  calibrationSeeds: z.number().int().positive(),
  validationSeeds: z.number().int().positive(),
  failures: z.number().int().nonnegative(),
  repairRate: z.number().min(0).max(1),
  backtrackRate: z.number().min(0).max(1),
  durationMs: z.number().nonnegative(),
  bands: z.object({
    contender: bandDistributionEntrySchema,
    playoff: bandDistributionEntrySchema,
    average: bandDistributionEntrySchema,
    weaker: bandDistributionEntrySchema,
  }),
  identities: z.record(z.string().min(1), distributionEntrySchema),
  measured: z.object({
    anchorFulfillment: z.number().min(0).max(1),
    extraEliteRate: z.number().min(0).max(1),
    extraEliteExpected: z.number().min(0).max(1),
    superTeamIncidence: z.number().min(0).max(1),
    poolLegalityFailures: z.number().int().nonnegative(),
    selectionFailures: z.number().int().nonnegative(),
    generationFailures: z.number().int().nonnegative(),
    orderInvarianceFailures: z.number().int().nonnegative(),
  }),
  gates: z.object({
    orderedBandMedians: z.boolean(),
    quotas: z.boolean(),
    roleCoverage: z.boolean(),
    identities: z.boolean(),
    poolLegality: z.boolean(),
    selectionLegality: z.boolean(),
    failureRate: z.boolean(),
    minBandSeparation: z.boolean(),
    anchorFulfillment: z.boolean(),
    extraEliteWithinTolerance: z.boolean(),
    superTeamIncidence: z.boolean(),
    orderInvariance: z.boolean(),
    heldOutPassShare: z.number().min(0).max(1),
    heldOutPass: z.boolean(),
  }),
  targetsWritten: z.boolean(),
  targetsPath: z.string().nullable(),
  validateOnly: z.boolean(),
  pass: z.boolean(),
});
export type SeasonRostersCalibrateReport = z.infer<typeof seasonRostersCalibrateReportSchema>;
export const seasonDraftCalibrateReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('season draft calibrate'),
  calibrationSeeds: z.number().int().positive(),
  validationSeeds: z.number().int().positive(),
  durationMs: z.number().nonnegative(),
  variety: distributionEntrySchema,
  minSafePerOffer: z.number().int().nonnegative(),
  safeAvailabilityShare: z.number().min(0).max(1),
  selectableGroupCoverageShare: z.number().min(0).max(1),
  duplicateDrafts: z.number().int().nonnegative(),
  draftFailures: z.number().int().nonnegative(),
  generationFailures: z.number().int().nonnegative(),
  bands: z.object({
    contender: distributionEntrySchema,
    playoff: distributionEntrySchema,
    average: distributionEntrySchema,
    weaker: distributionEntrySchema,
  }),
  gates: z.object({
    minSafe: z.boolean(),
    zeroDuplicates: z.boolean(),
    zeroDraftFailures: z.boolean(),
    zeroGenerationFailures: z.boolean(),
    selectableGroupCoverage: z.boolean(),
    heldOutVarietyPassShare: z.number().min(0).max(1),
    heldOutVarietyPass: z.boolean(),
    heldOutSafePassShare: z.number().min(0).max(1),
    heldOutSafePass: z.boolean(),
    heldOutCoveragePassShare: z.number().min(0).max(1),
    heldOutCoveragePass: z.boolean(),
    heldOutStrengthPassShare: z.number().min(0).max(1),
    heldOutStrengthPass: z.boolean(),
  }),
  targetsWritten: z.boolean(),
  targetsPath: z.string().nullable(),
  pass: z.boolean(),
});
export type SeasonDraftCalibrateReport = z.infer<typeof seasonDraftCalibrateReportSchema>;
export const overallsDistributionBandSchema = z.object({
  label: z.string().min(1),
  targetPercent: z.number().min(0).max(100),
  count: z.number().int().nonnegative(),
  percentage: z.number().min(0).max(100),
  median: z.number().min(0).max(100).nullable(),
  min: z.number().min(0).max(100),
  max: z.number().min(0).max(100),
});
export const overallsDistributionEraSchema = z.object({
  count: z.number().int().nonnegative(),
  bands: z.array(overallsDistributionBandSchema),
});
export const overallsDistributionReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('data overalls-distribution'),
  dataVersion: z.string().min(1).max(64),
  cohortVersion: z.string().min(1).max(64),
  total: z.number().int().nonnegative(),
  overall: z.object({
    median: z.number().min(0).max(100).nullable(),
    range: z.tuple([z.number().min(0).max(100), z.number().min(0).max(100)]),
    min: z.number().min(0).max(100),
    max: z.number().min(0).max(100),
    sample: z.number().int().nonnegative(),
  }),
  bands: z.array(overallsDistributionBandSchema),
  perEra: z.record(z.string().min(1), overallsDistributionEraSchema),
});
export type OverallsDistributionReport = z.infer<typeof overallsDistributionReportSchema>;
export const defenseBpmEraSchema = z.object({
  eraId: z.string().min(1),
  sample: z.number().int().nonnegative(),
  correlation: z.number().min(-1).max(1).nullable(),
});
export const defenseBpmCorrelationReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('data defense-bpm-correlation'),
  dataVersion: z.string().min(1).max(64),
  totalRows: z.number().int().nonnegative(),
  sample: z.number().int().nonnegative(),
  excluded: z.number().int().nonnegative(),
  correlation: z.number().min(-1).max(1).nullable(),
  pass: z.boolean(),
  perEra: z.array(defenseBpmEraSchema),
});
export type DefenseBpmCorrelationReport = z.infer<typeof defenseBpmCorrelationReportSchema>;
const seasonGamePlayerMinutesSchema = z.object({
  side: z.enum(['home', 'away']),
  playerVersionId: playerVersionIdSchema,
  actualSeconds: z.number().int().nonnegative(),
  targetSeconds: z.number().int().nonnegative(),
  deviationSeconds: z.number().int(),
  reasons: z.array(seasonRotationDeviationReasonSchema),
});
export const seasonGameSimulateReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('season game simulate'),
  fixtureId: z.string().min(1).max(64),
  seed: z.string().regex(/^[0-9a-f]{16,64}$/),
  outcome: z.enum(['completed', 'forfeit', 'no-legal-five-both']),
  winner: z.enum(['home', 'away']).nullable(),
  home: z.object({
    teamId: z.string().min(1).max(64),
    displayName: z.string().min(1).max(96),
    score: z.number().int().nonnegative().nullable(),
  }),
  away: z.object({
    teamId: z.string().min(1).max(64),
    displayName: z.string().min(1).max(96),
    score: z.number().int().nonnegative().nullable(),
  }),
  overtimePeriods: z.number().int().nonnegative(),
  forfeit: z
    .object({
      losingFranchiseId: franchiseIdSchema,
      trigger: seasonForfeitTriggerSchema,
    })
    .nullable(),
  engineVersion: z.string().min(1).max(64),
  dataVersion: z.string().min(1).max(64),
  profileVersion: z.string().min(1).max(64),
  gameVersion: z.string().min(1).max(64),
  rotationVersion: z.string().min(1).max(64),
  playerMinutes: z.array(seasonGamePlayerMinutesSchema),
  substitutions: z.array(seasonSubstitutionSchema),
  unitStints: z.array(seasonUnitStintSchema),
  foulOuts: z.array(seasonFoulOutSchema),
  deviations: z.array(seasonRotationDeviationSchema),
  invariantFailures: z.array(z.string().min(1)),
  pass: z.boolean(),
});
export type SeasonGameSimulateReport = z.infer<typeof seasonGameSimulateReportSchema>;
const seasonGameFixtureStatsSchema = z.object({
  fixtureId: z.string().min(1).max(64),
  preset: seasonRotationPresetSchema.nullable(),
  sample: z.number().int().nonnegative(),
  starterSecondsMedian: z.number().nonnegative(),
  benchSecondsMedian: z.number().nonnegative(),
  benchRoleMedianSeconds: z.array(z.number().nonnegative()).length(5),
  failures: z.object({
    games: z.number().int().nonnegative(),
    checks: z.number().int().nonnegative(),
    determinism: z.number().int().nonnegative(),
  }),
});
export const seasonGameCalibrateReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('season game calibrate'),
  fixtures: z.array(
    z.object({
      fixtureId: z.string().min(1).max(64),
      preset: seasonRotationPresetSchema.nullable(),
    }),
  ),
  calibrationSeedCount: z.number().int().nonnegative(),
  validationSeedCount: z.number().int().nonnegative(),
  workers: z.number().int().min(1),
  durationMs: z.number().nonnegative(),
  fixtureStats: z.array(seasonGameFixtureStatsSchema),
  gates: z.object({
    zeroFailures: z.boolean(),
    starterOrdering: z.boolean(),
    benchOrdering: z.boolean(),
    benchRoleNonIncreasing: z.boolean(),
    heldOutPassShare: z.number().min(0).max(1),
    heldOutPass: z.boolean(),
  }),
  chunkingIndependent: z.boolean(),
  targetsWritten: z.boolean(),
  targetsPath: z.string().nullable(),
  pass: z.boolean(),
});
export type SeasonGameCalibrateReport = z.infer<typeof seasonGameCalibrateReportSchema>;
export const seasonBlockSimulateReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('season block simulate'),
  runId: z.string().min(1).max(64),
  blockIndex: z.number().int().min(0).max(8),
  expectedRevision: z.number().int().nonnegative(),
  rotationDigest: z.string().regex(/^[0-9a-f]{32}$/),
  completedRounds: z.number().int().min(0).max(82),
  summaryCount: z.number().int().min(1).max(150),
  retainedDetailCount: z.number().int().min(0).max(10),
  objectiveId: seasonObjectiveIdSchema.nullable(),
  stateRevision: z.number().int().nonnegative(),
  stateDigest: z.string().regex(/^[0-9a-f]{32}$/),
  digest: z.string().regex(/^[0-9a-f]{32}$/),
  durationMs: z.number().nonnegative(),
  auditFailures: z.array(z.string()),
  rejection: z.string().nullable(),
  pass: z.boolean(),
});
export type SeasonBlockSimulateReport = z.infer<typeof seasonBlockSimulateReportSchema>;
export const seasonBlockAuditReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('season block audit'),
  runId: z.string().min(1).max(64),
  blockIndex: z.number().int().min(0).max(8),
  digest: z.string().regex(/^[0-9a-f]{32}$/),
  recomputedDigest: z.string().regex(/^[0-9a-f]{32}$/),
  auditFailures: z.array(z.string()),
  pass: z.boolean(),
});
export type SeasonBlockAuditReport = z.infer<typeof seasonBlockAuditReportSchema>;
export const seasonFullSimulateReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('season full simulate'),
  runId: z.string().min(1).max(64),
  blockDigests: z
    .array(
      z.object({
        blockIndex: z.number().int().min(0).max(8),
        digest: z.string().regex(/^[0-9a-f]{32}$/),
        durationMs: z.number().nonnegative(),
      }),
    )
    .length(9),
  finalDigest: z.string().regex(/^[0-9a-f]{32}$/),
  totalDurationMs: z.number().nonnegative(),
  summaries: z.number().int().positive(),
  stateRevision: z.number().int().nonnegative(),
  stateDigest: z.string().regex(/^[0-9a-f]{32}$/),
  stateChainContinuity: z.boolean(),
  finalInjuryCount: z.number().int().nonnegative(),
  finalTransactionCount: z.number().int().nonnegative(),
  tradeWindowsOpened: z.number().int().nonnegative(),
  auditFailures: z.array(z.string()),
  pass: z.boolean(),
});
export type SeasonFullSimulateReport = z.infer<typeof seasonFullSimulateReportSchema>;
export const seasonBenchmarkReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.enum([
    'season benchmark block',
    'season benchmark full',
    'season benchmark determinism',
    'season benchmark persistence',
  ]),
  runId: z.string().min(1).max(64),
  durationMs: z.number().nonnegative(),
  budgetMs: z.number().nullable(),
  withinBudget: z.boolean().nullable(),
  digest: z.string().nullable(),
  identicalDigests: z.boolean().nullable(),
  perBlock: z
    .array(
      z.object({
        blockIndex: z.number().int().min(0).max(8),
        digest: z.string().regex(/^[0-9a-f]{32}$/),
        durationMs: z.number().nonnegative(),
      }),
    )
    .optional(),
  persistence: z.unknown().nullable(),
  auditFailures: z.array(z.string()),
  outPath: z.string().nullable(),
  pass: z.boolean(),
});
export type SeasonBenchmarkReport = z.infer<typeof seasonBenchmarkReportSchema>;
export const seasonHomeCourtCalibrateReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('season home-court calibrate'),
  profileVersion: z.literal('season-home-court-v1'),
  constants: z.object({
    homeDefensiveCommunication: z.number().min(0).max(1),
    awayTurnoverPressure: z.number().min(0).max(1),
  }),
  targetHomeWinRate: z.literal(0.575),
  calibrationSeedCount: z.number().int().nonnegative(),
  validationSeedCount: z.number().int().nonnegative(),
  neutralHomeWinRate: z.number().min(0).max(1),
  achievedHomeWinRate: z.number().min(0).max(1),
  gamesSimulated: z.number().int().positive(),
  durationMs: z.number().nonnegative(),
  gates: z.object({
    neutralBaseline: z.boolean(),
    withinTolerance: z.boolean(),
    possessionStable: z.boolean(),
    monotonic: z.boolean(),
  }),
  targetsWritten: z.boolean(),
  targetsPath: z.string().nullable(),
  pass: z.boolean(),
});
export type SeasonHomeCourtCalibrateReport = z.infer<typeof seasonHomeCourtCalibrateReportSchema>;
export const seasonEffectsSensitivityReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('season effects sensitivity'),
  fixtureId: z.string().min(1),
  fatigueLevels: z.array(z.number().int().nonnegative()),
  rows: z.array(
    z.object({
      fatigueBp: z.number().int().nonnegative(),
      shooterDelta: z.number(),
      handlerDelta: z.number(),
      defenseDelta: z.number(),
      securityDelta: z.number(),
      assistDelta: z.number(),
      helpDelta: z.number(),
    }),
  ),
  durationMs: z.number().nonnegative(),
});
export type SeasonEffectsSensitivityReport = z.infer<typeof seasonEffectsSensitivityReportSchema>;
export const seasonEffectsDistributionReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('season effects distribution'),
  fixtureIds: z.array(z.string().min(1)),
  seedFrom: z.number().int().nonnegative(),
  seedTo: z.number().int().nonnegative(),
  gamesSimulated: z.number().int().nonnegative(),
  completedGames: z.number().int().nonnegative(),
  scoringDeltaMedian: z.number(),
  turnoverDeltaMedian: z.number(),
  assistDeltaMedian: z.number(),
  scoringWithinEnvelope: z.number().min(0).max(1),
  turnoverWithinEnvelope: z.number().min(0).max(1),
  assistWithinEnvelope: z.number().min(0).max(1),
  checkFailures: z.number().int().nonnegative(),
  determinismFailures: z.number().int().nonnegative(),
  durationMs: z.number().nonnegative(),
});
export type SeasonEffectsDistributionReport = z.infer<typeof seasonEffectsDistributionReportSchema>;
export const seasonEffectsRolesReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('season effects roles'),
  rows: z.array(
    z.object({
      fixtureId: z.string().min(1),
      starterMedianFatigue: z.number().int().nonnegative(),
      benchMedianFatigue: z.number().int().nonnegative(),
    }),
  ),
  starterOrderingPass: z.boolean(),
  benchOrderingPass: z.boolean(),
  durationMs: z.number().nonnegative(),
});
export type SeasonEffectsRolesReport = z.infer<typeof seasonEffectsRolesReportSchema>;
export const seasonEffectsCalibrateReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('season effects calibrate'),
  targetsVersion: z.union([
    z.literal(SEASON_EFFECT_TARGETS_VERSION),
    z.literal(SEASON_EFFECT_TARGETS_LEGACY_VERSION),
  ]),
  calibrationSeedCount: z.number().int().nonnegative(),
  validationSeedCount: z.number().int().nonnegative(),
  calibrationGames: z.number().int().nonnegative(),
  heldOutGames: z.number().int().nonnegative(),
  calibrationScoringDeltaMedian: z.number(),
  calibrationTurnoverDeltaMedian: z.number(),
  calibrationAssistDeltaMedian: z.number(),
  heldOutWithinEnvelopeShare: z.number().min(0).max(1),
  stableUnitMedianBp: z.number().int().nonnegative(),
  shuffledUnitMedianBp: z.number().int().nonnegative(),
  chemistrySeparationBp: z.number().int(),
  gates: z.object({
    zeroFailures: z.boolean(),
    determinism: z.boolean(),
    productionEnvelopes: z.boolean(),
    heldOutPassShare: z.boolean(),
    rotationOrdering: z.boolean(),
    chemistrySeparation: z.boolean(),
    sensitivityMonotonic: z.boolean(),
  }),
  targetsWritten: z.boolean(),
  targetsPath: z.string().nullable(),
  durationMs: z.number().nonnegative(),
});
export type SeasonEffectsCalibrateReport = z.infer<typeof seasonEffectsCalibrateReportSchema>;
export const seasonM25GateSchema = z.object({
  key: z.string().min(1).max(64),
  observed: z.number(),
  target: z.number(),
  tolerance: z.number().nullable(),
  min: z.number().nullable(),
  max: z.number().nullable(),
  status: calibrationMetricStatusSchema,
  pass: z.boolean(),
  sample: z.number().int().nonnegative(),
  minimumSample: z.number().int().nonnegative(),
});
export type SeasonM25GateReport = z.infer<typeof seasonM25GateSchema>;
export const seasonHealthCalibrateReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('season health calibrate'),
  targetsVersion: z.literal(SEASON_INJURY_TARGETS_VERSION),
  calibrationSeeds: z.number().int().nonnegative(),
  validationSeeds: z.number().int().nonnegative(),
  seasonsSimulated: z.number().int().nonnegative(),
  exposures: z.number().int().nonnegative(),
  injuries: z.number().int().nonnegative(),
  meanRiskBasisPoints: z.number().nonnegative(),
  severityShares: z.object({
    minor: z.number().min(0).max(1),
    moderate: z.number().min(0).max(1),
    major: z.number().min(0).max(1),
    seasonEnding: z.number().min(0).max(1),
  }),
  durationMeans: z.object({
    minor: z.number(),
    moderate: z.number(),
    major: z.number(),
  }),
  sameGameReturnRate: z.number().min(0).max(1),
  recurrenceGapBp: z.number(),
  seasonEndingRate: z.number().min(0).max(1),
  standingsGapBp: z.number(),
  monotonic: z.object({
    minutes: z.boolean(),
    fatigue: z.boolean(),
    durability: z.boolean(),
  }),
  gates: z.object({
    incidence: z.boolean(),
    severityDistribution: z.boolean(),
    durationMeans: z.boolean(),
    sameGameReturn: z.boolean(),
    recurrenceLift: z.boolean(),
    seasonEndingRate: z.boolean(),
    monotonicMinutes: z.boolean(),
    monotonicFatigue: z.boolean(),
    monotonicDurability: z.boolean(),
    standingsIndependent: z.boolean(),
    heldOut: z.boolean(),
  }),
  metrics: z.array(seasonM25GateSchema),
  skippedGates: z.array(z.string().min(1)),
  targetsWritten: z.boolean(),
  targetsPath: z.string().nullable(),
  durationMs: z.number().nonnegative(),
});
export type SeasonHealthCalibrateReport = z.infer<typeof seasonHealthCalibrateReportSchema>;
export const seasonTradeCalibrateReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('season trade calibrate'),
  targetsVersion: z.literal(SEASON_TRADE_TARGETS_VERSION),
  calibrationSeeds: z.number().int().nonnegative(),
  validationSeeds: z.number().int().nonnegative(),
  seasonsSimulated: z.number().int().nonnegative(),
  aiTradesMean: z.number(),
  aiTradesMin: z.number().int().nonnegative(),
  aiTradesMax: z.number().int().nonnegative(),
  acceptedTrades: z.number().int().nonnegative(),
  packageMix: z.object({
    '1-1': z.number().int().nonnegative(),
    '2-2': z.number().int().nonnegative(),
    '1-2': z.number().int().nonnegative(),
    '2-1': z.number().int().nonnegative(),
  }),
  illegalRosterFailures: z.number().int().nonnegative(),
  duplicateOwnershipFailures: z.number().int().nonnegative(),
  valueBandFailures: z.number().int().nonnegative(),
  chemistryPairs: z.number().int().nonnegative(),
  chemistryPairFailures: z.number().int().nonnegative(),
  zeroStateNewPairFailures: z.number().int().nonnegative(),
  deterministicOffers: z.boolean(),
  gates: z.object({
    aiTradesPerSeason: z.boolean(),
    zeroIllegal: z.boolean(),
    zeroDuplicateOwnership: z.boolean(),
    valueBands: z.boolean(),
    deterministicOffers: z.boolean(),
    chemistryInvariants: z.boolean(),
    packageMix: z.boolean(),
    heldOut: z.boolean(),
    zeroInfluenceOnly: z.boolean().optional(),
    cashCaps: z.boolean().optional(),
    noNegativeBalance: z.boolean().optional(),
    cashReconciliation: z.boolean().optional(),
    inquiryExchangeLimits: z.boolean().optional(),
    noDuplicateQuota: z.boolean().optional(),
    influenceNeverBypass: z.boolean().optional(),
  }),
  metrics: z.array(seasonM25GateSchema),
  skippedGates: z.array(z.string().min(1)),
  targetsWritten: z.boolean(),
  targetsPath: z.string().nullable(),
  durationMs: z.number().nonnegative(),
});
export type SeasonTradeCalibrateReport = z.infer<typeof seasonTradeCalibrateReportSchema>;
export const seasonInfluenceCalibrateReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('season influence calibrate'),
  targetsVersion: z.literal(SEASON_INFLUENCE_TARGETS_VERSION),
  calibrationSeeds: z.number().int().nonnegative(),
  validationSeeds: z.number().int().nonnegative(),
  seasonsSimulated: z.number().int().nonnegative(),
  balanceChecks: z.number().int().nonnegative(),
  reconciliationFailures: z.number().int().nonnegative(),
  incomeIdentityFailures: z.number().int().nonnegative(),
  debtFrequency: z.number().min(0).max(1),
  debtBoundaries: z.number().int().nonnegative(),
  capViolations: z.number().int().nonnegative(),
  objectiveEvaluations: z.number().int().nonnegative(),
  objectiveSuccessRate: z.number().min(0).max(1).nullable(),
  extraOfferSpendShare: z.number().min(0).max(1),
  extraOfferWindows: z.number().int().nonnegative(),
  rehabSpendShare: z.number().min(0).max(1),
  rehabInjuries: z.number().int().nonnegative(),
  gates: z.object({
    ledgerReconciliation: z.boolean(),
    incomeIdentity: z.boolean(),
    debtFrequency: z.boolean(),
    zeroCapViolations: z.boolean(),
    objectiveSuccessRate: z.boolean(),
    extraOfferSpendRate: z.boolean(),
    rehabSpendRate: z.boolean(),
    heldOut: z.boolean(),
    zeroFloor: z.boolean().optional(),
    campaignRewards: z.boolean().optional(),
    inquiryPurchases: z.boolean().optional(),
    tradeCash: z.boolean().optional(),
    cashReconciliation: z.boolean().optional(),
  }),
  metrics: z.array(seasonM25GateSchema),
  skippedGates: z.array(z.string().min(1)),
  targetsWritten: z.boolean(),
  targetsPath: z.string().nullable(),
  durationMs: z.number().nonnegative(),
});
export type SeasonInfluenceCalibrateReport = z.infer<typeof seasonInfluenceCalibrateReportSchema>;
export const seasonRunReproduceReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('season run reproduce'),
  runId: z.string().min(1).max(64),
  rootSeed: z.string().min(1).max(64),
  eraId: z.string().min(1).max(64),
  commandCount: z.number().int().nonnegative(),
  replayedCount: z.number().int().nonnegative(),
  blockCount: z.number().int().nonnegative(),
  expectedCommandLogDigest: z.string().regex(/^[0-9a-f]{32}$/),
  expectedFinalStateDigest: z.string().regex(/^[0-9a-f]{32}$/),
  expectedAlmanacDigest: z.string().regex(/^[0-9a-f]{32}$/),
  expectedChampionFranchiseId: z.string().min(1).max(64),
  verifiedChainFacts: z.boolean(),
  verifiedInitialRun: z.boolean(),
  verifiedFinalStateDigest: z.boolean(),
  verifiedAwards: z.boolean(),
  verifiedChampion: z.boolean(),
  firstDivergence: z
    .object({
      ordinal: z.number().int().nonnegative().nullable(),
      commandId: z.string().max(64),
      kind: z.enum([
        'state-digest',
        'result-digest',
        'game-result',
        'award-result',
        'trade-grade-result',
        'champion',
        'chain-fact',
        'rejected-command',
        'free-agency',
        'campaign-offers',
        'campaign-evaluations',
        'board',
        'inquiries',
        'ai-response',
        'ai-counter',
        'ai-transaction',
        'rehab-outcome',
        'value-trends',
        'influence-cash',
      ]),
      detail: z.string().min(1),
    })
    .nullable(),
  divergences: z.array(z.string().min(1)).max(50),
  pass: z.boolean(),
});
export type SeasonRunReproduceReport = z.infer<typeof seasonRunReproduceReportSchema>;
export const seasonPostseasonAuditReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('season postseason audit'),
  runId: z.string().min(1).max(64),
  championFranchiseId: z.string().nullable(),
  gameCount: z.number().int().nonnegative(),
  failures: z.array(z.string().min(1)).max(200),
  counts: z.object({
    duplicateTeams: z.number().int().nonnegative(),
    missingTeams: z.number().int().nonnegative(),
    invalidFeeders: z.number().int().nonnegative(),
    incorrectHomeCourt: z.number().int().nonnegative(),
    gamesAfterClinching: z.number().int().nonnegative(),
    inconsistentSummaries: z.number().int().nonnegative(),
    championCompletionMismatch: z.number().int().nonnegative(),
    digestMismatch: z.number().int().nonnegative(),
  }),
  pass: z.boolean(),
});
export type SeasonPostseasonAuditReport = z.infer<typeof seasonPostseasonAuditReportSchema>;
export const seasonPostseasonCalibrateReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('season postseason calibrate'),
  targetsVersion: z.literal(SEASON_POSTSEASON_TARGETS_VERSION),
  calibrationSeeds: z.number().int().nonnegative(),
  validationSeeds: z.number().int().nonnegative(),
  seasonsSimulated: z.number().int().nonnegative(),
  gamesPlayed: z.number().int().nonnegative(),
  seriesCompleted: z.number().int().nonnegative(),
  seriesLengthMean: z.number().nonnegative(),
  upsetRate: z.number().min(0).max(1),
  upsetGames: z.number().int().nonnegative(),
  homeAdvantage: z.number().min(0).max(1),
  homeGames: z.number().int().nonnegative(),
  advancementByStrength: z.number().min(0).max(1),
  strengthDecidedSeries: z.number().int().nonnegative(),
  awardPlausibility: z.number().min(0).max(1).nullable(),
  awardChecks: z.number().int().nonnegative(),
  forfeits: z.number().int().nonnegative(),
  integrityFailures: z.number().int().nonnegative(),
  champions: z.number().int().nonnegative(),
  duplicateTeamFailures: z.number().int().nonnegative(),
  missingTeamFailures: z.number().int().nonnegative(),
  bothInvalidGames: z.number().int().nonnegative(),
  gates: z.object({
    championPerSeason: z.boolean(),
    zeroDuplicateTeams: z.boolean(),
    zeroMissingTeams: z.boolean(),
    zeroBothInvalidGames: z.boolean(),
    seriesLength: z.boolean(),
    upsetRate: z.boolean(),
    homeAdvantage: z.boolean(),
    advancementByStrength: z.boolean(),
    awardPlausibility: z.boolean(),
    forfeitRate: z.boolean(),
    zeroIntegrityFailures: z.boolean(),
    heldOut: z.boolean(),
  }),
  metrics: z.array(seasonM25GateSchema),
  skippedGates: z.array(z.string().min(1)),
  targetsWritten: z.boolean(),
  targetsPath: z.string().nullable(),
  durationMs: z.number().nonnegative(),
  pass: z.boolean(),
});
export type SeasonPostseasonCalibrateReport = z.infer<typeof seasonPostseasonCalibrateReportSchema>;
export const seasonCampaignCalibrateReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('season campaign calibrate'),
  targetsVersion: z.literal(SEASON_CAMPAIGN_TARGETS_VERSION),
  calibrationSeeds: z.number().int().nonnegative(),
  validationSeeds: z.number().int().nonnegative(),
  seasonsSimulated: z.number().int().nonnegative(),
  eligibleCheckpoints: z.number().int().nonnegative(),
  offersGenerated: z.number().int().nonnegative(),
  offerPerCheckpointFailures: z.number().int().nonnegative(),
  unsupportedFactFailures: z.number().int().nonnegative(),
  duplicateRewardFailures: z.number().int().nonnegative(),
  branchViolations: z.number().int().nonnegative(),
  evolutionViolations: z.number().int().nonnegative(),
  determinismFailures: z.number().int().nonnegative(),
  orderInvarianceFailures: z.number().int().nonnegative(),
  completedShare: z.number().min(0).max(1),
  breakthroughShare: z.number().min(0).max(1),
  gates: z.object({
    offersPerCheckpoint: z.boolean(),
    zeroUnsupportedFact: z.boolean(),
    zeroDuplicateReward: z.boolean(),
    zeroBranch: z.boolean(),
    zeroEvolution: z.boolean(),
    determinism: z.boolean(),
    orderInvariance: z.boolean(),
    heldOut: z.boolean(),
  }),
  metrics: z.array(seasonM25GateSchema),
  skippedGates: z.array(z.string().min(1)),
  targetsWritten: z.boolean(),
  targetsPath: z.string().nullable(),
  durationMs: z.number().nonnegative(),
});
export type SeasonCampaignCalibrateReport = z.infer<typeof seasonCampaignCalibrateReportSchema>;
export const seasonCampaignAuditReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('season campaign audit'),
  eligibleCheckpoints: z.number().int().nonnegative(),
  offersGenerated: z.number().int().nonnegative(),
  offerPerCheckpointFailures: z.number().int().nonnegative(),
  unsupportedFactFailures: z.number().int().nonnegative(),
  duplicateRewardFailures: z.number().int().nonnegative(),
  branchViolations: z.number().int().nonnegative(),
  evolutionViolations: z.number().int().nonnegative(),
  determinismFailures: z.number().int().nonnegative(),
  orderInvarianceFailures: z.number().int().nonnegative(),
  pass: z.boolean(),
});
export type SeasonCampaignAuditReport = z.infer<typeof seasonCampaignAuditReportSchema>;
export const seasonFreeAgencyAuditCountsSchema = z.object({
  windowOrderFailures: z.number().int().nonnegative(),
  candidateUniquenessFailures: z.number().int().nonnegative(),
  featuredFailures: z.number().int().nonnegative(),
  canonicalFailures: z.number().int().nonnegative(),
  declarationFailures: z.number().int().nonnegative(),
  traceFailures: z.number().int().nonnegative(),
  bandCapFailures: z.number().int().nonnegative(),
  signingCapFailures: z.number().int().nonnegative(),
  spendCapFailures: z.number().int().nonnegative(),
  ledgerFailures: z.number().int().nonnegative(),
  transactionFailures: z.number().int().nonnegative(),
  ownershipFailures: z.number().int().nonnegative(),
  effectsFailures: z.number().int().nonnegative(),
});
export type SeasonFreeAgencyAuditCountsReport = z.infer<typeof seasonFreeAgencyAuditCountsSchema>;
export const seasonFreeAgencyAuditReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('season free-agency audit'),
  runId: z.string().min(1).max(64),
  rootSeed: z.string().min(1).max(64),
  windows: z.number().int().nonnegative(),
  signings: z.number().int().nonnegative(),
  canonicalIdentities: z.number().int().nonnegative(),
  counts: seasonFreeAgencyAuditCountsSchema,
  failures: z.array(z.string().min(1)).max(200),
  pass: z.boolean(),
});
export type SeasonFreeAgencyAuditReport = z.infer<typeof seasonFreeAgencyAuditReportSchema>;
export const seasonFreeAgencyCalibrateReportSchema = z.object({
  schemaVersion: z.literal(1),
  command: z.literal('season free-agency calibrate'),
  targetsVersion: z.literal(SEASON_FREE_AGENCY_TARGETS_VERSION),
  calibrationSeeds: z.number().int().nonnegative(),
  validationSeeds: z.number().int().nonnegative(),
  seasonsSimulated: z.number().int().nonnegative(),
  windowsOpened: z.number().int().nonnegative(),
  signings: z.number().int().nonnegative(),
  uniqueIdentities: z.number().int().nonnegative(),
  canonicalReuse: z.number().int().nonnegative(),
  candidateTotal: z.number().int().nonnegative(),
  candidateShortfalls: z.number().int().nonnegative(),
  declaredTargets: z.number().int().nonnegative(),
  signingsByBand: z.object({
    contender: z.number().int().nonnegative(),
    playoff: z.number().int().nonnegative(),
    average: z.number().int().nonnegative(),
    weaker: z.number().int().nonnegative(),
  }),
  interestByBand: z.object({
    featured: z.number().int().nonnegative(),
    role: z.number().int().nonnegative(),
    development: z.number().int().nonnegative(),
    emergency: z.number().int().nonnegative(),
  }),
  winsByBand: z.object({
    featured: z.number().int().nonnegative(),
    role: z.number().int().nonnegative(),
    development: z.number().int().nonnegative(),
    emergency: z.number().int().nonnegative(),
  }),
  skipShare: z.number().min(0).max(1),
  bandCapViolations: z.number().int().nonnegative(),
  signingCapViolations: z.number().int().nonnegative(),
  spendCapViolations: z.number().int().nonnegative(),
  linkFailures: z.number().int().nonnegative(),
  traceAuditFailures: z.number().int().nonnegative(),
  effectsFailures: z.number().int().nonnegative(),
  influenceDecideFailures: z.number().int().nonnegative(),
  eliteExclusionFailures: z.number().int().nonnegative(),
  oneOutlierFailures: z.number().int().nonnegative(),
  richGetRicherFailures: z.number().int().nonnegative(),
  signedAboveDraftedMedianShare: z.number().min(0).max(1),
  determinismProbe: z.object({ probed: z.boolean(), identical: z.boolean() }),
  summaryIdentityProbe: z.object({ probed: z.boolean(), identical: z.boolean() }),
  gates: z.object({
    windowsOpened: z.boolean(),
    bandSigningCaps: z.boolean(),
    threeSigningsPerSeason: z.boolean(),
    sixInfluencePerSeason: z.boolean(),
    linkReconciliation: z.boolean(),
    traceAudit: z.boolean(),
    effectsInvariants: z.boolean(),
    rosterLegality: z.boolean(),
    ownershipRows: z.boolean(),
    eliteExclusion: z.boolean(),
    oneOutlierCeiling: z.boolean(),
    noRichGetRicher: z.boolean(),
    influenceTieBreak: z.boolean(),
    determinismProbe: z.boolean(),
    candidateQuality: z.boolean(),
    interestActivity: z.boolean(),
    summaryIdentity: z.boolean(),
    heldOut: z.boolean(),
  }),
  metrics: z.array(seasonM25GateSchema),
  skippedGates: z.array(z.string().min(1)),
  targetsWritten: z.boolean(),
  targetsPath: z.string().nullable(),
  durationMs: z.number().nonnegative(),
});
export type SeasonFreeAgencyCalibrateReport = z.infer<typeof seasonFreeAgencyCalibrateReportSchema>;
